spring:
  profiles:
    include: default
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false  
  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:mem:db;DB_CLOSE_DELAY=-1"
    username: "sa"
    password: "sa"
    
  # Show or not log for each sql query
  jpa:
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"

firebase:
  enabled: false
