spring:
  profiles:
    active: ${spring.profiles.active}
  main:
    banner-mode: "off"
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  freemarker:
    template-loader-path: "classpath:/templates"
    suffix: ".ftl"
  h2:
    console:
      enabled: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: "none"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
  liquibase:
    enabled: true
    change-log: "classpath:db/changelog/db.changelog-master.yaml"

phonenumbercode:
  expire: 5 # hours
  maxcache: 10000

cors:
  allowedorigins: "http://localhost:8080,http://localhost:8100"

firebase:
  enabled: false

server:
  port: "8080"

logging:
  level:
    ROOT: INFO