spring:
  main:
    banner-mode: "off"
  freemarker:
    check-template-location: true
    template-loader-path: "classpath:/templates/"
    suffix: ".ftl"
  h2:
    console:
      enabled: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: "none"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
  liquibase:
    enabled: true
    change-log: "classpath:db/changelog/db.changelog-master.yaml"

phonenumbercode:
  expire: 5 # hours
  maxcache: 10000

server:
  port: "8080"

logging:
  level:
    ROOT: INFO
